/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Ygz3gGbUVZP
 */
import { Button } from "@/app/components/ui/button/button";
import {
  DropdownMenuTrigger,
  DropdownMenuItem,
  DropdownMenuContent,
  DropdownMenu,
} from "@/app/components/ui/dropdown/dropdown-menu";
import { SVGProps } from "react";

export function Splitbutton() {
  return (
    <div className="mt-4">
      <DropdownMenu>
        <div className="flex">
          <Button size={"sm"} className="rounded-none rounded-l-lg">
            Primary Action
          </Button>
          <DropdownMenuTrigger asChild>
            <Button
              size={"sm"}
              variant="default"
              className="ml-0.5 rounded-none rounded-r-lg"
            >
              <ArrowDownIcon className="h-4 w-4" />
            </Button>
          </DropdownMenuTrigger>
        </div>
        <DropdownMenuContent className="w-56">
          <DropdownMenuItem>Action 1</DropdownMenuItem>
          <DropdownMenuItem>Action 2</DropdownMenuItem>
          <DropdownMenuItem>Action 3</DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  );
}

function ArrowDownIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 5v14" />
      <path d="m19 12-7 7-7-7" />
    </svg>
  );
}
